# modules/tips.py
# ─────────────────────────────────────────────────────────────
# SEED FILE — used only on first run to populate the database.
# After seeding, all tip and alert data is managed through
# the database directly via DB Browser or the admin panel.
#
# Bemba translations verified by native speaker.
# Nyanja translations generated by NLLB-200 where not available.
# ─────────────────────────────────────────────────────────────

TIPS = [
    {
        "category": "mobile_money",
        "english": "CYBER TIP: Your Mobile Money PIN is like the key to your cattle kraal or your house. If you give it to a stranger, they can take everything. Keep your PIN a secret from everyone.",
        "bemba":   "Mobile Money PIN yobe yaba nge fungulo lya ng'anda yobe nangu kraal yobe ya ng'ombe. Nga waipela ku muntu we ushaishiba, kuti afumyako fyonse. Bika PIN yobe mu bwafya, wipela umuntu nangu umo.",
        "nyanja":  ""
    },
    {
        "category": "smishing",
        "english": "CYBER TIP: If you get a message saying \"You have won K5,000, click here to claim,\" ignore it. Clicking the link is like opening your door to a thief. Delete the message immediately.",
        "bemba":   "Nga wapokelela ubutumwa uleti \"Mwacimfya or Mwawina K5,000, tinikeni apa mule claim-a,\" ubusheni. Ukufinya link kwaba nge kwisula umwinshi ku mubomba. Fumyeni ubutumwa ubwene bwangu.",
        "nyanja":  ""
    },
    {
        "category": "verification",
        "english": "CYBER TIP: Before you send money to anyone, always wait for the phone to show you the NAME of the person. If the name is not who you expect, press \"Cancel\" immediately.",
        "bemba":   "Nga mule tumina umuntu ndalama, lindeni fye telephone ilange ishina lyakwe. Nga ishina tali ilyo mule fwaya ku tinika \"Cancel\" bwangu.",
        "nyanja":  ""
    },
    {
        "category": "reporting",
        "english": "CYBER TIP: If a scammer tries to steal from you, dial *707#. This tells the government who the thief is so they can block their line and protect other people in your community.",
        "bemba":   "Nga kabolala aleesha ukumibila, kutinika *707#. Ici cilafwilisha boma ukwishiba kabolala no kumu fumya numberla yakwe.",
        "nyanja":  ""
    },
]

SAMPLE_ALERTS = [
    {
        "category": "smishing",
        "severity": "HIGH",
        "english": "URGENT WARNING: Fraudsters are sending fake Airtel prize messages across Zambia right now. Do NOT click any links or call back unknown numbers.",
        "bemba":   "ICHILANGILILO CIKULU: Ba Kabolala bale tuma ama message ya pa Airtel ayabufi mu Zambia pali ino nshita. Mwikwata.",
        "nyanja":  "Chenjelesani: Ma kawalala ya tumiza nkalata pa lamya ye ya kamba ati mwa wina ndalama kuli ba airtel. Mu sa segule ma message ye ya chokela Ku ma nambala ye siazibika."
    },
    {
        "category": "mobile_money",
        "severity": "HIGH",
        "english": "URGENT WARNING: A new mobile money scam is targeting MTN users in rural areas. Scammers pretend to be MTN agents and ask for your PIN. Never share your PIN.",
        "bemba":   "ICHILANGILILO CIKULU: Ubu ububi bule konka aba bomfi ba MTN Mobile Money. Ba Kabolaa bale landa ukuti ba bomba ku MTN no kulomba PIN yenu. Mwipela umuntu nangu umo PIN yenu.",
        "nyanja":  "Chenjelesani: Ma kawalala a'ndalama pa foni achita monga ni ogwilitsa nchito ku MTN mu ma minzi. ma kawalala aya a'nama ati ni o'thandizdira ku MTN no funsa PIN yanu ya ndalama mu lamya. osa pasa PIN kuli ali yense."
    },
    {
        "category": "smishing",
        "severity": "HIGH",
        "english": "URGENT: Scammers are calling people saying they sent money to you by mistake. They will ask you to send it back. DO NOT send any money. Check your balance first or wait for the network to handle it.",
        "bemba":   "ICHILANGILILO CIKULU: Ba Kabolala balikwita abantu baleebela ati batumina ndalama kuli imwe mu cilubo. Balamilomba ukuti mubweshe ndalama. MWITUMA nangu ndalama nangu shimo. Moneni balance yenu pa mobile money, nangu loleleni network ibombelepo.",
        "nyanja":  "Zofunika kwambili: Ma kawalala ba nama boza ku antu ati baku tumizilani ndalama molakwika no kamba ati bu ba bwezele. aza ku pempani ati mu a'bwezele ndalama mwa musanga. musa a'tumileni zili zonse, koma mu one ngati ndalama zanu za pa phone zi kalimo olo mu yembekeze aku MTN olo airtel ku gwiliza nchito yao."
    },
    {
        "category": "smishing",
        "severity": "HIGH",
        "english": "URGENT: If you receive a 5-digit code via SMS that you did not ask for, DO NOT share it with anyone who calls you. They are trying to lock you out of your own phone.",
        "bemba":   "ICHILANGILILO CIKULU: Nga mwapokelela code ya mpendwa isano pa SMS iyo mulombele, MWIBAPELA nangu umo uyo akumwita. Balefwaya ukumifumya pa foni yenu no kuikoma.",
        "nyanja":  "Chenjelesani: Muka pokelela nkalata pa foni na ma numbala yali five yene simuna fune, musa ipase kuli ali yense aza ku tumilani foni. Bafuna kumi komelani foni yanu."
    },
    {
        "category": "mobile_money",
        "severity": "HIGH",
        "english": "WARNING: Scammers are promising \"Government Fertilizer\" or \"Farmer Grants\" via SMS but asking for a registration fee first. This is a trap. Never pay money to receive a \"free\" gift.",
        "bemba":   "ICHILANGILILO CIKULU: Ababifi baletumina ama SMS baleetla ati pali \"Imbuto sha Buteko\" nangu, Nga balomba ndalama shaku lembesha pakutendeka. Mwituma ndalama pakupokelela icintu ico baleeti \"takuli kulipila\".",
        "nyanja":  "Chenjezo: Achigawenga akulonjeza \"Feteleza wa Boma\" kapena \"Thandizo la Alimi\" kudzera pa SMS koma akupempha kaye chindapusa cholembetsa. Uwu ndi msampha. Osalipira ndalama kuti mulandire mphatso \"yaulere\"."
    },
    {
        "category": "smishing",
        "severity": "HIGH",
        "english": "WARNING: A new vishing attack is targeting mobile banking users in Zambia. Do not give your PIN to anyone calling you.",
        "bemba":   "",
        "nyanja":  ""
    },
]


def get_all_tips():
    return TIPS


def get_tip_in_language(tip: dict, language: str) -> str:
    lang = language.lower()
    if lang == "bemba" and tip.get("bemba"):
        return tip["bemba"]
    elif lang == "nyanja" and tip.get("nyanja"):
        return tip["nyanja"]
    return tip["english"]
